# === Basic Site Information ===
site_name: "archive" # Replace with your desired site title
# Use the future Cloudflare Pages URL or your custom domain
site_url: "https://your-project-name.pages.dev/" # IMPORTANT: Update this later!
# Optional: Description for search engines
# site_description: "网站描述"
# Optional: Author
# site_author: "你的名字"

# === MkDocs Settings ===
# Directory containing Markdown source files
docs_dir: docs
# Directory where static site will be built (default is 'site', which is fine)
# site_dir: site

# === Theme Configuration (mkdocs-simple-blog) ===
theme:
  name: material
  features:
    - navigation.indexes
  # sidebar: true
  # navigation_depth: 3
  # menu: false
  # Optional: Customize theme features (refer to mkdocs-simple-blog docs)
  # logo: assets/logo.png # Example logo path (relative to docs_dir)
  # favicon: assets/faviconico
  # palette: # Example color scheme override
  #   scheme: default
  #   primary: indigo
  #   accent: blue
  # font:
  #   text: Roboto
  #   code: Roboto Mono

# === Plugins ===
plugins:
  - search # Built-in search plugin
  - gen-files:
      scripts:
        - gen_pages.py # or any other name or path
  # - blog:
  #     # Directory containing blog posts (relative to docs_dir)
  #     # blog_dir: blog # Matches where we moved posts earlier
  #     # Optional: How many posts per page in listings
  #     posts_per_page: 10
  # Optional: Customize archive URL/title etc. (see plugin docs)
  # archive_url_format: "archive/{year}"
  # archive_title_format: "Archive {year}"
  # - literate-nav:
  #     nav_file: SUMMARY.md
# === Navigation (Optional but recommended) ===
# Defines the top navigation bar. If omitted, MkDocs tries to auto-generate.
nav:
  #   - "博客": "data" # Link to the blog index page generated by the plugin
  # - '分类': blog/category/ # Link to categories page (if theme supports)
  # - '标签': blog/tag/ # Link to tags page (if theme supports)
  - "Home": "index.md" # Link to docs/about.md

# === Markdown Extensions (Optional but useful) ===
markdown_extensions:
  # Standard extensions
  - toc:
      permalink: true # Adds clickable links to headings
  - admonition # Adds special note/warning boxes
  - footnotes
  # PyMdown Extensions (if installed)
  - pymdownx.highlight: # Code syntax highlighting
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences # Advanced fenced code blocks
  - pymdownx.details # Collapsible blocks
  - pymdownx.magiclink # Auto-links
  - pymdownx.tasklist: # Checkboxes
      custom_checkbox: true
  # - pymdownx.emoji: # Emoji support
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
